---
# playbook.yml
# run with: ansible-playbook -i localhost playbook.yml

- name: A local play
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - shell: |
        echo 'Enabled: Yes'
      register: cmd

    - name: "Show cmd.stdout"
      debug:
        msg: "cmd.stdout is: {{ cmd.stdout }}"

    - name: "Show cmd.stdout.find() result"
      debug:
        msg: "cmd.stdout.find('Enabled: Yes') is: {{ cmd.stdout.find('Enabled: Yes') }}"

    - name: "Check cmd.stdout using 'in' syntax"
      debug:
        msg: "cmd.stdout has 'Enabled: Yes': {{ cmd.stdout }}"
      when: '"Enabled: Yes" in cmd.stdout'

    - name: "Check cmd.stdout using 'not in' syntax"
      debug:
        msg: "cmd.stdout does not have 'Enabled: Yes': {{ cmd.stdout }}"
      when: '"Enabled: Yes" not in cmd.stdout'

    - name: "Check cmd.stdout using find() syntax"
      debug:
        msg: "cmd.stdout has 'Enabled: Yes': {{ cmd.stdout }}"
      when: 'cmd.stdout.find("Enabled: Yes") != -1'

    - name: "Check cmd.stdout using find() syntax"
      debug:
        msg: "cmd.stdout does not have 'Enabled: Yes': {{ cmd.stdout }}"
      when: 'cmd.stdout.find("Enabled: Yes") == -1'
