---
# playbook.yml
# run with: ansible-playbook -i localhost playbook.yml

- name: A local play
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    test_data: "{{ lookup('file', 'test.txt') }}"

  tasks:
    - name: Show file from vars
      debug:
        msg: "contents of test.txt are: {{ test_data }}"

    - name: Show file from tasks
      debug:
        msg: "Reading contets of file during tasks: {{ lookup('file', 'test.txt') }}"

    - name: Interpolate scary file contents
      shell: |
        echo -n "{{ lookup('file', 'scary-contents.txt') }}"
      register: scary_contents

    - name: Show that scary contents did bad things
      debug:
        var: "scary_contents.stdout_lines"
