---
# playbook.yml
# run with: ansible-playbook -i localhost playbook.yml

- name: A local play
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    Ubuntu:
      foo: "This is the Ubuntu.foo value"
      bar: "This is the Ubuntu.bar value"
    MacOSX:
      foo: "This is the MacOSX.foo value"
      bar: "This is the MacOSX.bar value"

  tasks:
    - name: show stuff
      debug:
        var: "{{ ansible_distribution }}"
